### ISSUE TITLE
[功能建议] 喂养与体力机制

### ISSUE THREAD

**Issue by luoxiawuchen** [inrhor/imipetCore#2]
1、为宠物新增体力条（活力）机制，和生命对应。
2、自定义，攻击，行走等不同行为的体力消耗。
3、通过喂养回复体力，自定义宠物需要喂养的对应物品
例如： A宠物 只接受 物品描述（或名称）含有关键字 "宠物食物" 的物品进行喂养，回复体力
宠物食物可以通过lore描述（活力恢复: +5），恢复对应的体力数值（类似于旧版的imipet）

**Comment by inrhor** [comment]
已支持，具体方式要自行客制，通过ImiPetCore文档的Kether概览操作挂钩属性相关语句完成实现
