### ISSUE TITLE
[BUG] 宠物可以被放上马鞍、可以被命名牌直接修改名称

### ISSUE THREAD

**Issue by luoxiawuchen** [inrhor/imipetCore#4]
![image](https://user-images.githubusercontent.com/64759847/197373629-1624c26a-4bf8-4a9a-b0a3-73d1b4451e24.png)
![image](https://user-images.githubusercontent.com/64759847/197373673-7bf34321-346b-4c25-b519-c86c4968e6c1.png)

**Comment by inrhor** [comment]
Fixed
