### ISSUE TITLE
[功能建议] Kether语句 检测获取宠物受到的伤害来源、设置宠物是否反击

### ISSUE THREAD

**Issue by luoxiawuchen** [inrhor/imipetCore#5]
发现宠物在被其他玩家或怪物攻击时，会呆在原地
不知能否添加相关语句，以便控制宠物AI是否作出反击
![image](https://user-images.githubusercontent.com/64759847/197376328-01fc199e-0006-4044-8352-6acba56ac74c.png)
![image](https://user-images.githubusercontent.com/64759847/197376346-7709cf54-2b64-4bac-93a4-a8ed3de0f174.png)
![image](https://user-images.githubusercontent.com/64759847/197376351-3707c3dc-76d1-4d7a-855d-979b58dadc10.png)

**Comment by inrhor** [comment]
已修复 + 已支持
