### ISSUE TITLE
[功能建议] 添加宠物PVP开关命令

### ISSUE THREAD

**Issue by luoxiawuchen** [inrhor/imipetCore#6]
例如，当玩家使用 /pet pvp false 时，宠物无法被其他玩家伤害，同时不再攻击任何玩家（不参与pvp）
这主要是应用于一些RPG场景，避免在组队攻略副本时造成尴尬的误伤

同时希望可以支持proskillapi的技能免伤
proskillapi是skillapi弃坑后的新分支，为1.16+以后的高版本提供支持
https://www.spigotmc.org/resources/proskillapi-create-custom-races-classes-skills-spells-with-an-easy-online-editor.91913/

**Comment by inrhor** [comment]
已对ProSkillAPI、SkillAPI支持宠物免疫玩家技能伤害

关于玩家攻击伤害宠物请自行客制
相关链接：
- https://www.imipet.com/docs/config/action
- https://www.imipet.com/docs/overview/kether#%E8%8E%B7%E5%BE%97%E5%AE%A0%E7%89%A9%E4%BA%94%E7%A7%92%E5%86%85%E5%8F%97%E5%88%B0%E6%9D%A5%E6%BA%90%E7%9A%84%E5%AE%9E%E4%BD%93
